# Dictionary

Empty dict example:

In [16]:
empty_dict={}

Dictionary are used to store pair as `key:value`, you can retrive values by key, differently from list where you use a positional index:

In [17]:
sample_dict={"first":3, "second":88, "third":123}
print(sample_dict)

{'first': 3, 'second': 88, 'third': 123}


In [18]:
print(sample_dict["second"])
print(sample_dict["third"])

88
123


And you can insert new `value` with a new `key`:

In [19]:
sample_dict["last"]=999

In [21]:
print(sample_dict)

{'first': 3, 'second': 88, 'third': 123, 'last': 999}


In [ ]:
Is possible to iterate throught dictionaries and get the keys:

In [8]:
for i in sample_dict:
    print(i)

first
second
third


In [ ]:
Or get the pair `key:value`

In [26]:
for i in sample_dict.items():
    print(f"Print the tuple: {i}")
    print(f"Print the single elements of the touple: {i[0]} and {i[1]}\n")

Print the tuple: ('first', 3)
Print the single elements of the touple: first and 3

Print the tuple: ('second', 88)
Print the single elements of the touple: second and 88

Print the tuple: ('third', 123)
Print the single elements of the touple: third and 123

Print the tuple: ('last', 999)
Print the single elements of the touple: last and 999



Or unpack the touple directly:

In [28]:
for key,value in sample_dict.items():
    print(f"This is the key: {key} and this is the value: {value}")

This is the key: first and this is the value: 3
This is the key: second and this is the value: 88
This is the key: third and this is the value: 123
This is the key: last and this is the value: 999


In [ ]:
See https://docs.python.org/3/tutorial/datastructures.html#dictionaries for more details.

In [ ]:
Exercies: https://pynative.com/python-dictionary-exercise-with-solutions/

In [15]:
print(s[0:4])

this


# More on list

See official docs: https://docs.python.org/3/tutorial/datastructures.html#more-on-lists

You can select slice of list with the following notation `start:stop`, stop is excluded. If start ort stop are omitted, is implicit the beginning of the end.

In [53]:
mylist=[1,5,3,7,5,6,4,5]

In [54]:
print("Select a slice: ",mylist[3:6])
print("Implicit end: ",mylist[3:])
print("Implicit start: ",mylist[:6])

Select a slice:  [7, 5, 6]
Implicit end:  [7, 5, 6, 4, 5]
Implicit start:  [1, 5, 3, 7, 5, 6]


You can start indexing by end using negative indexes:

In [55]:
mylist[-1]

5

Append element to a list:

In [56]:
empty_list=[]
empty_list.append(4)
empty_list.append(7)
empty_list.append(34)
empty_list.append(22)
empty_list.append(-4)
print(empty_list)

[4, 7, 34, 22, -4]


Sort element of a list:

In [57]:
unsorted_list=[4, 7, 34, 22, -4]
unsorted_list.sort()
print(unsorted_list)

[-4, 4, 7, 22, 34]


Reverse the order of a list:

In [62]:
mylist=[4, 7, 34, 22, -4]
mylist.reverse()
print(mylist)

[-4, 22, 34, 7, 4]


Nested list:

In [58]:
nested = [ [1,2,3], [4,5,6],[7,8,9]  ]
print(nested)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Access to the inner lists:

In [59]:
print("First nested:" ,nested[0])
print("Second nested:" ,nested[1])


First nested: [1, 2, 3]
Second nested: [4, 5, 6]


# Exercies

Try to solve this set of exercies on lists: https://pynative.com/python-list-exercise-with-solutions/ .



# Numpy 101

Numpy is a python library that is used to facilitate linear algebra operation.
First of all import the numpy library:

In [64]:
import numpy as np

And generate a numpy array starting from a list:


In [69]:
a = np.array([1,5,2,3,4,45])
print(a)

[ 1  5  2  3  4 45]


They are similar to lists, but support several algebra and maths operation:


In [73]:
print(a*10) # product by scalar
print(a+1) # elementwise addition
print(a+a) # sum between array

[ 10  50  20  30  40 450]
[ 2  6  3  4  5 46]
[ 2 10  4  6  8 90]


Using nested lists you can define matrices (2d array):

In [76]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


And you can query the shape of the numpy object using:

In [78]:
matrix.shape

(4, 3)

Some exercise on numpy:
https://pynative.com/python-numpy-exercise/